---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meter-monitor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "meter-monitor.name" . }}
    helm.sh/chart: {{ include "meter-monitor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.configs }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
...
