---
replicaCount: 1

image:
  repository: 'docker-repo/cob/meter_monitor'
  tag:        '1.0.1-19dd9c9'
  pullPolicy: 'Always'

config:
  base_uri: "/meters"

  db:
    host:     'localhost'
    dbname:   'meters'
    username: 'meters'
    password: 'secret'

  auth:
    ldap:
      server:
      base_dn:
      username_attribute:
      user_binding:
      admin_binding:
      admin_pass:
    cas:
      server:
      uri:

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: 'kubetest'
      paths: ['/meters']

  tls:
    - secretName: 'cert-wildcard'
      hosts:
        - 'kubetest'

...
